version: '3.4'
services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: p4ssw0rd
    ports:
      - 3306:3306
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
    restart: on-failure

