version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
        
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
